[package]
name = "umem_proto_generated"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
serde = { workspace = true }
rmcp = {workspace = true }
schemars = {workspace = true}

[build-dependencies]
tonic-build = {version="0.12", features = ["prost"]}

