[package]
name = "umem"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
umem_search = {path = "crates/umem_search"}
umem_doc_parser = {path = "crates/umem_doc_parser"}
umem_vector = {path = "crates/umem_vector"}
anyhow = "1.0.98"
lazy_static = "1.5.0"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
serde_json = "1.0.140"

[dependencies]
umem_search = { workspace = true }
umem_doc_parser = { workspace = true}
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
serde_json = { workspace = true }
