[package]
name = "umem_search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
directories = "6.0.0"
memmap2 = "0.9.5"
mime = "0.3.17"
mime_guess = "2.0.5"
num_cpus = "1.17.0"
tantivy = "0.24.1"
