name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo registry
      uses: useblacksmith/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build (Release)
      if: github.ref == 'refs/heads/main'
      run: cargo build --release --verbose
    
    - name: Build (Debug)
      if: github.ref != 'refs/heads/main'
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
